import { expect, type FrameLocator, type Page } from '@playwright/test';
import { TIMEOUTS } from '../constants/timeouts';
import { logger } from '../logger';
import { focusTab, isVisualTabMode } from './tabVisualHelper';
import { AssertionUtils } from '../utils/AssertionUtils';

const YOPMAIL_URL = 'https://yopmail.com/';

/**
 * YOPmail inbox helpers for Create New User welcome-mail verification.
 * Locators follow the recorded YOPmail flow (Login → Check Inbox → #refresh → ifmail).
 */
export class YopmailPage {
  constructor(private readonly page: Page) {}

  private loginField() {
    return this.page.getByRole('textbox', { name: 'Login' }).or(this.page.locator('#login'));
  }

  /** Recorded locator: getByTitle('Check Inbox @yopmail.com') */
  private checkInboxButton() {
    return this.page.getByTitle('Check Inbox @yopmail.com').first();
  }

  private mailFrame(): FrameLocator {
    return this.page.frameLocator('iframe[name="ifmail"]');
  }

  private inboxFrame(): FrameLocator {
    return this.page.frameLocator('iframe[name="ifinbox"]');
  }

  private toFullEmail(emailOrLocalPart: string): string {
    return emailOrLocalPart.includes('@')
      ? emailOrLocalPart.toLowerCase()
      : `${emailOrLocalPart.toLowerCase()}@yopmail.com`;
  }

  private toLocalPart(emailOrLocalPart: string): string {
    return emailOrLocalPart.includes('@')
      ? emailOrLocalPart.split('@')[0].toLowerCase()
      : emailOrLocalPart.toLowerCase();
  }

  /**
   * Asserts YOPmail inbox is open for the same address pasted into Live+ Add User.
   * Verifies login field local-part and inbox header full email match.
   */
  async assertInboxEmailMatches(expectedEmail: string): Promise<void> {
    const fullEmail = this.toFullEmail(expectedEmail);
    const localPart = this.toLocalPart(expectedEmail);

    await expect(
      this.loginField(),
      `YOPmail Login field must contain local-part "${localPart}" from Live+`,
    ).toHaveValue(localPart);
    await expect(
      this.page.getByText(fullEmail, { exact: false }).first(),
      `YOPmail inbox must display the same email "${fullEmail}" entered in Live+`,
    ).toBeVisible({ timeout: TIMEOUTS.SLOW_UI_MS });

    logger.info(`YOPmail inbox verified — matches Live+ email: ${fullEmail}`);
  }

  /**
   * Opens YOPmail and loads the inbox for the generated local-part / full email.
   * Must use the same unique address that was pasted into Live+ Add User.
   */
  async openInbox(emailOrLocalPart: string): Promise<void> {
    const localPart = this.toLocalPart(emailOrLocalPart);
    const fullEmail = this.toFullEmail(emailOrLocalPart);

    await this.page.goto(YOPMAIL_URL, { waitUntil: 'domcontentloaded' });
    await AssertionUtils.assertVisible(
      this.page.getByRole('link', { name: /YOPmail, Disposable email/i }).first(),
      'YOPmail home should be visible',
    );
    await AssertionUtils.assertVisible(this.loginField(), 'YOPmail Login field should be visible');

    await this.loginField().click();
    await this.loginField().fill(localPart);
    await this.checkInboxButton().click();

    await this.assertInboxEmailMatches(fullEmail);
    await focusTab(this.page, `YOPmail inbox — ${fullEmail}`);
    logger.info(`YOPmail inbox opened for ${fullEmail}`);
  }

  /** Recorded: page.locator('#refresh').click() — dismisses ad popup if it blocks the button. */
  async refreshInbox(): Promise<void> {
    const popup = this.page.locator('#r_parent.r_popup');
    if (await popup.isVisible({ timeout: 1500 }).catch(() => false)) {
      await this.page.keyboard.press('Escape').catch(() => undefined);
      await popup.waitFor({ state: 'hidden', timeout: 5000 }).catch(() => undefined);
    }

    const refresh = this.page.locator('#refresh');
    await expect(refresh, 'YOPmail #refresh should be visible').toBeVisible({
      timeout: TIMEOUTS.SLOW_UI_MS,
    });
    await refresh.click({ force: true });
  }

  /**
   * Extracts temp password from welcome body, e.g.
   * "Please use this link and password Axv1ukbO#C to log in."
   */
  extractPasswordFromBody(body: string): string | null {
    const patterns = [
      /password\s+(\S+)\s+to\s+log\s+in/i,
      /password\s+([A-Za-z0-9#@$%&*!_\-.]+)/i,
    ];
    for (const pattern of patterns) {
      const match = body.match(pattern);
      if (match?.[1]) {
        return match[1].replace(/[*.]+$/g, '').trim();
      }
    }
    return null;
  }

  /**
   * Polls inbox for "New user added to Live+" and returns the temporary password.
   * Password is generated by the app and only available in YOPmail — never hardcoded.
   */
  async waitForLivePlusWelcomePassword(
    expectedFirstName: string,
    expectedLastName?: string,
    expectedEmail?: string,
    timeoutMs = 180_000,
  ): Promise<string> {
    let lastBody = '';
    let extractedPassword = '';

    await focusTab(this.page, 'YOPmail — waiting for Live+ welcome email');

    if (expectedEmail) {
      await this.assertInboxEmailMatches(expectedEmail);
    }

    await expect
      .poll(
        async () => {
          if (isVisualTabMode()) {
            await this.page.bringToFront();
          }
          await this.refreshInbox();

          const welcomeInList = this.inboxFrame()
            .getByText(/New user added to Live\+/i)
            .first();
          if (await welcomeInList.isVisible({ timeout: 3000 }).catch(() => false)) {
            await welcomeInList.click();
          }

          const bodyLocator = this.mailFrame().locator('body');
          if (!(await bodyLocator.isVisible({ timeout: 3000 }).catch(() => false))) {
            return false;
          }

          lastBody = (await bodyLocator.innerText().catch(() => '')) || '';
          if (!/New user added to Live\+|added to Live\+/i.test(lastBody)) {
            return false;
          }

          const password = this.extractPasswordFromBody(lastBody);
          if (!password) {
            return false;
          }

          extractedPassword = password;
          return true;
        },
        {
          message: `Waiting for Live+ welcome password in YOPmail for "${expectedFirstName}"`,
          timeout: timeoutMs,
          intervals: [2_000, 3_000, 5_000],
        },
      )
      .toBeTruthy();

    expect(
      lastBody,
      `Welcome email should mention first name "${expectedFirstName}"`,
    ).toMatch(new RegExp(expectedFirstName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'));
    if (expectedLastName) {
      expect(
        lastBody,
        `Welcome email should mention last name "${expectedLastName}"`,
      ).toMatch(new RegExp(expectedLastName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'));
    }

    expect(extractedPassword, 'Welcome email password must not be empty').not.toBe('');
    await focusTab(this.page, 'YOPmail — welcome password extracted');
    logger.info('Live+ welcome email received; password extracted from YOPmail');
    return extractedPassword;
  }
}

export function createYopmailPage(page: Page): YopmailPage {
  return new YopmailPage(page);
}
